name: marketplace_v4
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Implementacion de la libreria graphql que nos ayudara para la realizacion
  #de operaciones a nivel de graphql.
  graphql_flutter: ^5.0.0
  
  curved_navigation_bar: ^0.3.7
  #Navigation bar estilo curvo
  responsive_framework: ^0.1.0
  #
  carousel_pro: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  #Importacion de imagenes
  assets:
    - images/

  #Implementacion de fondos  
  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500

